version: '3' # specify version of docker compose you want to use
services:
  redis-server:
    image: 'redis'
  node-app:
    restart: on-failure
    build: . # look in the current directory for a docker file
    ports:
      - "4001:8081" # local:container
